name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
    run: |
      echo "Instlling dependencies"
      sudo apt-get install libdart6-all-dev
    - name: Build and Run
    run: |
      dart Main.dart
