name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dart
    run: |
      sudo apt-get update
      sudo apt-get install apt-transport-https
      sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'

      sudo apt-get update
      sudo apt-get install dart

      echo "After installing the SDK, add its bin directory to your PATH. For example, use the following command to change PATH in your active terminal session"
      export PATH="$PATH:/usr/lib/dart/bin"
    - name: Install Dependencies
    run: pub get
    - name: Build and Run
    run: |
      dart Main.dart
